### ISSUE TITLE
Asset Upload

### ISSUE THREAD

**Issue by juicycleff** [grommet/grommet-cms#6]
After uploading an image or asset, the file throws an error. The file us saved in the upload filder, but cant be retrieved in the cms after upload.

**Comment by karatechops** [comment]
Hey @juicycleff I've just posted a fix for this in 7ac546e. In dev mode the auth is turned off so you do not need to login every time you refresh the page however the asset upload feature expects a user. 7ac546e applies a conditional to handle this.

We should probably make it clearer the CMS is not totally stable. I have a very large update I will be making to it whenever I get a few free days. I'm very excited to introduce the new changes as they'll include image processing/optimizing and AWS S3 asset offloading. I'm also in the process of fully refactoring the content block system.
