### ISSUE TITLE
grommet-cms

### ISSUE THREAD

**Issue by pc-tradelab** [grommet/grommet-cms#7]
Hello,

is this repo still under development ?

Thanks !

**Comment by karatechops** [comment]
Unfortunately I haven't had time to update this repo. I do build on this CMS codebase almost daily and plan on updating the public repo when I get a free moment but it will most likely be early 2018 before I can get around to it.

**Comment by pc-tradelab** [comment]
Thanks for your answer. I hope to see your work soon !
